config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments, :only => [:create, :destroy]
  end

  get 'my_events', to: 'events#my_events'
  get 'all_events', to: 'events#all_events'

  devise_for :users

  root 'events#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    if user  
      can :manage, :all   
    end  
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  validates :event_id, :body, :presence => true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates :user_id, :event_start, :event_end, :recurrence, :title, presence: true

  def next_date(date)
    case recurrence
    when 'Each day' || ''
      date.next_day
    when 'Each week'
      date + 7.days
    when 'Each month'
      date.next_month
    when 'Each year'
      date.next_year
    end
  end

  def accepted_dates
    current_date = event_start.clone
    dates = []
    until current_date > event_end
      dates << current_date if current_date <= event_end
      current_date = next_date(current_date)
    end
    dates
  end

  def occurs_at?(date)
    accepted_dates.include?(date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, :email, uniqueness: true, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url
  end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]
  before_filter :authenticate_user!, :only => [:create]

  def create
    @event = Event.find(params[:event_id])
    comment = @event.comments.build(comment_params)
    comment.user = current_user

    if comment.save
      redirect_to event_path(@event)
    else
      redirect_to event_path(@event)
    end
  end

  def destroy
    @comment.delete
    render json: { success: true }
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource only: [:new, :edit, :create, :update, :destroy]
  skip_load_resource only: [:create]

  def index
    @events = Event.all
    @events_by_date = @events.group_by(&:event_start)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_events
    @events = current_user.events
  end

  def all_events
    @events = Event.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :event_start, :event_end, :recurrence, :user_id)
    end

    def repeat_params
      params.require(:repeat).permit(:event_id, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_owner(item)
    current_user == item.user
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
    START_DAY = :monday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def find_events_at(date)
    @events.select do |event|
      event.occurs_at?(date)
    end
  end
end

app/views/comments/_form.html.slim
= form_for [@event, @event.comments.new] do |f|
  = f.text_area :body, class: 'form-control'
  br
  = f.submit "Добавить комментарий", class: 'btn btn-primary btn-sm'

app/views/comments/_index.html.slim
- @comments.each do |comment|
  div
    b Comment:
    = comment.body
  div
    b Author: 
    = comment.user.name

app/views/comments/_show.html.slim
- @event.comments.each do |comment|
  .col-md-12 data-coment_id="#{comment.id}" data-event_id="#{@event.id}"
    div
      b Comment:
      = comment.body
    div
      b Author: 
      = comment.user.name
      
    - if user_owner(comment)
      .btn.btn-danger.btn-xs.deleteAction Delete comment

app/views/events/_form.html.slim
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      ul
      - @event.errors.full_messages.each do |message|
        li= message
  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :event_start
    = f.text_field :event_start
    
  .field
    = f.label :event_end
    = f.text_field :event_end 
  
  .field
    = f.label :recurrence
    = f.select :recurrence, [['None', nil], ['Each day'],['Each week'],['Each month'], ['Each year']]
  
  .actions
    = f.submit

app/views/events/all_events.slim
h1 My events
.container
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
      th #
      th Event Title
      th Date
      
      tbody
        - @events.each do |event|
          tr
          td= event.id
          td= link_to event.title, event
          td= event.event_start 

app/views/events/edit.html.slim
h1 Editing event

= render 'form'

app/views/events/index.html.slim
h1 Event calendar

#events
  h2#month
    = link_to "<< Previous", date: @date.prev_month
    = @date.strftime("%B %Y")
    = link_to "Next >>", date: @date.next_month

  = calendar @date do |date|

    = date.day
    - selected_events = find_events_at(date)
    ul
      - selected_events.each do |event|
        li= link_to event.title, event_path(event.id)

- if user_signed_in?
  = link_to 'New Event', new_event_path, class: 'btn btn-default'

app/views/events/my_events.html.slim
h1 My events
.container
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
      th #
      th Event Title
      th Date
      
      tbody
        - @events.each do |event|
          tr
          td= event.id
          td= event.title
          td= event.event_start 

app/views/events/new.html.slim
h1 New event

= render 'form'

app/views/events/show.html.slim
p#notice 
  = notice

p
  strong Title:
  = @event.title

p
  strong User:
  = @event.user.name

h3 Event comments
= render 'comments/show'
- if user_signed_in?
  = render 'comments/form'

app/views/layouts/application.html.slim
doctype
html
head
  title Calendar
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body
  .container
    .navbar.navbar-default
      .container-fluid
        .navbar-brand
          = link_to "Events", root_path
        .collapse.navbar-collapse
          = render "shared/links"

    = yield

app/views/shared/_links.html.slim
ul.nav.navbar-nav
  - if user_signed_in?
    li= link_to "My Profile", edit_user_registration_path
    li= link_to "Sign out", destroy_user_session_path, :method=>'delete'
    li= link_to "My events", my_events_path
    li= link_to "Event list", all_events_path
  - else
    li= link_to "Sign up", new_user_registration_path
    li= link_to "Sign in", new_user_session_path